paginate: 10 # pagination based on number of posts
paginate_path: "page:num"

# Site settings
title: phanstasmal	
email: phanstasmal@gmail.com
description: ":3"
baseurl: ""
url: "http://phanstasmal.github.io"
twitter_username: phanstasmal
github_username:  phanstasmal

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments

image_avatar: https://avatars1.githubusercontent.com/u/7008520?s=460